# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('Departamento', models.CharField(max_length=40, verbose_name='Departamento')),
                ('Inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicial')),
                ('Fim', models.DateTimeField(blank=True, null=True, verbose_name='Final')),
                ('Projeto', models.CharField(max_length=40, verbose_name='Projeto')),
                ('Atividade', models.CharField(max_length=40, verbose_name='Atividade')),
                ('Descricao', models.TextField(max_length=200, verbose_name='Descricao')),
                ('Status', models.CharField(default='Pendente', max_length=10, verbose_name='Status')),
                ('Horas', models.CharField(blank=True, max_length=30, null=True, verbose_name='Horas')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'Atividades',
                'permissions': (('Coordenador', 'Coordenador'), ('Funcionario', 'Funcionario'), ('RH', 'RH'), ('Financeiro', 'Financeiro'), ('Gerente', 'Gerente'), ('Diretor', 'Diretor'), ('Administrador', 'Administrador')),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Projeto', models.CharField(max_length=50, verbose_name='Projeto')),
                ('Responsavel', models.CharField(max_length=50, verbose_name='Responsavel')),
                ('Prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('Horas', models.IntegerField(blank=True, default='00', null=True, verbose_name='Horas')),
                ('Status', models.CharField(default='Pendente', max_length=20, verbose_name='Status')),
                ('Descricao', models.TextField(max_length=200, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Projetos',
                'verbose_name_plural': 'Projetos',
                'db_table': 'Projetos',
                'permissions': (('Coordenador', 'Coordenador'), ('Funcionario', 'Funcionario'), ('RH', 'RH'), ('Financeiro', 'Financeiro'), ('Gerente', 'Gerente'), ('Diretor', 'Diretor'), ('Administrador', 'Administrador')),
            },
        ),
    ]
