# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
    ]
