# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0002_auto_20170930_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
