# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0004_auto_20170930_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='Departamento',
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='Nome',
        ),
        migrations.AddField(
            model_name='atividades',
            name='Responsavel',
            field=models.CharField(default=0, max_length=50, verbose_name='Responsavel'),
            preserve_default=False,
        ),
    ]
