# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0005_auto_20170930_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividades',
            name='Prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
    ]
