# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0006_atividades_prazo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividades',
            name='Responsavel',
        ),
        migrations.AddField(
            model_name='atividades',
            name='Nome',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
