# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0007_auto_20170930_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='Responsavel',
            field=models.CharField(default='Selecione uma opção', max_length=50, verbose_name='Responsavel'),
        ),
    ]
