# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0010_auto_20171001_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividades',
            name='Horas',
            field=models.TimeField(blank=True, default='00:00:00', null=True, verbose_name='Horas'),
        ),
    ]
