# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Funcionarios', '0011_auto_20171002_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='Horas',
            field=models.IntegerField(blank=True, default='01', null=True, verbose_name='Horas'),
        ),
    ]
